---

cassandra_version: 311x
cassandra_apt_key: "http://www.apache.org/dist/cassandra/KEYS"
cassandra_apt_url: "deb http://www.apache.org/dist/cassandra/debian {{ cassandra_version }} main"

cassandra_user: cassandra
cassandra_group: cassandra

cassandra_cluster_name: "main"
cassandra_num_tokens: 256

cassandra_seed_provider_parameters_seeds: "{{ groups['cassandra_cluster'] | join(',') }}"

cassandra_storage_port: 7000
cassandra_ssl_storage_port: 7001

cassandra_listen_address: "{{ inventory_hostname }}"
cassandra_listen_interface: ""

cassandra_start_native_transport: "true"
cassandra_native_transport_port: 9042

cassandra_data_file_directories:
  - /opt/cassandra/data
cassandra_commitlog_directory: /opt/cassandra/comitlog
cassandra_saved_caches_directory: /opt/cassandra/saved_caches
cassandra_hints_directory: /opt/cassandra/hints
